site_name: Unigram
nav:
  - Home: index.md
  - Service Architecture: service-architecture.md
  - Microservices:
      - Index: services/README.md
      - Account Service: services/account-service.md
      - Broadcast Service: services/broadcast-service.md
      - Forum Service: services/forum-service.md
theme: readthedocs
